name: Lint Entire Codebase

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 * * * *
    
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          persistent-credentials: false
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
